# __Reading Tabular Data into DataFrames__

## Use the Pandas library to do statistics on tabular data.

*   Pandas is a widely-used Python library for statistics, particularly on tabular data.
*   Pandas DataFrames are 2-dimenstional tables whose columns have names and potentially have different data types.
*   Load it with `import pandas`.
*   Read a Comma Separated Values (CSV) data file with `pandas.read_csv`.
    *   Argument is the name of the file to be read.
    *   Assign result to a variable to store the data that was read.

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('data/gapminder_gdp_oceania.csv')

In [4]:
data

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
1,New Zealand,10556.57566,12247.39532,13175.67800,14463.91893,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

## Use `index_col` to specify that a column's values should be used as row headings.

*   Row headings are numbers (0 and 1 in this case).
*   What if we really want to index by country?
*   Pass the name of the column to `read_csv` as its `index_col` parameter to do this.

In [5]:
data = pd.read_csv('data/gapminder_gdp_oceania.csv', index_col='country')

In [6]:
data

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
New Zealand,10556.57566,12247.39532,13175.67800,14463.91893,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

## Use `DataFrame.info` to find out more about a dataframe.

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
gdpPercap_1952    2 non-null float64
gdpPercap_1957    2 non-null float64
gdpPercap_1962    2 non-null float64
gdpPercap_1967    2 non-null float64
gdpPercap_1972    2 non-null float64
gdpPercap_1977    2 non-null float64
gdpPercap_1982    2 non-null float64
gdpPercap_1987    2 non-null float64
gdpPercap_1992    2 non-null float64
gdpPercap_1997    2 non-null float64
gdpPercap_2002    2 non-null float64
gdpPercap_2007    2 non-null float64
dtypes: float64(12)
memory usage: 208.0+ bytes

## The `DataFrame.columns` variable stores information about the dataframe's columns.

*   Note that this is data, *not* a method.
    *   Like `math.pi`.
    *   So do not use `()` to try to call it.
*   Called a *member variable*, or just *member*.

In [13]:
data.columns

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

## Use `DataFrame.T` to transpose a dataframe.

*   Sometimes we want to treat columns as rows and vice versa.
*   Transpose (written `.T`) doesn't copy the data, just changes the program's view of it.
*   Like `columns`, it is a member variable.

In [12]:
data.T

country           Australia  New Zealand
gdpPercap_1952  10039.59564  10556.57566
gdpPercap_1957  10949.64959  12247.39532
gdpPercap_1962  12217.22686  13175.67800
gdpPercap_1967  14526.12465  14463.91893
gdpPercap_1972  16788.62948  16046.03728
gdpPercap_1977  18334.19751  16233.71770
gdpPercap_1982  19477.00928  17632.41040
gdpPercap_1987  21888.88903  19007.19129
gdpPercap_1992  23424.76683  18363.32494
gdpPercap_1997  26997.93657  21050.41377
gdpPercap_2002  30687.75473  23189.80135
gdpPercap_2007  34435.36744  25185.00911

## Use `DataFrame.describe` to get summary statistics about data.

* DataFrame.describe() gets the summary statistics of only the columns that have numerical data. 
* All other columns are ignored, unless you use the argument `include='all'`.

In [11]:
data.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
mean,10298.085650,11598.522455,12696.452430,14495.021790,16417.33338,17283.957605,18554.709840,20448.040160,20894.045885,24024.175170,26938.778040,29810.188275
std,365.560078,917.644806,677.727301,43.986086,525.09198,1485.263517,1304.328377,2037.668013,3578.979883,4205.533703,5301.853680,6540.991104
min,10039.595640,10949.649590,12217.226860,14463.918930,16046.03728,16233.717700,17632.410400,19007.191290,18363.324940,21050.413770,23189.801350,25185.009110
25%,10168.840645,11274.086022,12456.839645,14479.470360,16231.68533,16758.837652,18093.560120,19727.615725,19628.685413,22537.294470,25064.289695,27497.598692
50%,10298.085650,11598.522455,12696.452430,14495.021790,16417.33338,17283.957605,18554.709840,20448.040160,20894.045885,24024.175170,26938.778040,29810.188275
75%,10427.330655,11922.958888,12936.065215,14510.573220,16602.98143,17809.077557,19015.859560,21168.464595,22159.406358,25511.055870,28813.266385,32122.777857
max,10556.575660,12247.395320,13175.678000,14526.124650,16788.62948,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,30687.754730,34435.367440

## Reading Other Data

#### Read the data in `gapminder_gdp_americas.csv` (which should be in the same directory as `gapminder_gdp_oceania.csv`) into a variable called `americas` and display its summary statistics.

In [15]:
americas = pd.read_csv('data/gapminder_gdp_americas.csv', index_col='country')

In [21]:
americas

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850
Colombia,Americas,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,6117.361746,5755.259962,7006.580419
Costa Rica,Americas,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,6677.045314,7723.447195,9645.061420
Cuba,Americas,5586.538780,6092.174359,5180.755910,5690.268015,5305.445256,6380.494966,7316.918107,7532.924763,5592.843963,5431.990415,6340.646683,8948.102923
Dominican Republic,Americas,1397.717137,1544.402995,1662.137359,1653.723003,2189.874499,2681.988900,2861.092386,2899.842175,3044.214214,3614.101285,4563.808154,6025.374752
Ecuador,Americas,3522.110717,3780.546651,4086.114078,4579.074215,5280.994710,6679.623260,7213.791267,6481.776993,7103.702595,7429.455877,5773.044512,6873.262326
El Salvador,Americas,3048.302900,3421.523218,3776.803627,4358.595393,4520.246008,5138.922374,4098.344175,4140.442097,4444.231700,5154.825496,5351.568666,5728.353514
Guatemala,Americas,2428.237769,2617.155967,2750.364446,3242.531147,4031.408271,4879.992748,4820.494790,4246.485974,4439.450840,4684.313807,4858.347495,5186.050003
Haiti,Americas,1840.366939,1726.887882,1796.589032,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
Honduras,Americas,2194.926204,2220.487682,2291.156835,2538.269358,2529.842345,3203.208066,3121.760794,3023.096699,3081.694603,3160.454906,3099.728660,3548.330846
Jamaica,Americas,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,7121.924704,6994.774861,7320.880262
Mexico,Americas,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530,11977.574960
Nicaragua,Americas,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,2253.023004,2474.548819,2749.320965
Panama,Americas,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,7113.692252,7356.031934,9809.185636
Paraguay,Americas,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,4247.400261,3783.674243,4172.838464
Peru,Americas,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,5838.347657,5909.020073,7408.905561
Puerto Rico,Americas,3081.959785,3907.156189,5108.344630,6929.277714,9123.041742,9770.524921,10330.989150,12281.341910,14641.587110,16999.433300,18855.606180,19328.709010
Trinidad and Tobago,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,8792.573126,11460.600230,18008.509240
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.462990
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.805690

In [16]:
americas.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,4079.062552,4616.043733,4901.541870,5668.253496,6491.334139,7352.007126,7506.737088,7793.400261,8044.934406,8889.300863,9287.677107,11003.031625
std,3001.727522,3312.381083,3421.740569,4160.885560,4754.404329,5355.602518,5530.490471,6665.039509,7047.089191,7874.225145,8895.817785,9713.209302
min,1397.717137,1544.402995,1662.137359,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
25%,2428.237769,2487.365989,2750.364446,3242.531147,4031.408271,4756.763836,4258.503604,4140.442097,4439.450840,4684.313807,4858.347495,5728.353514
50%,3048.302900,3780.546651,4086.114078,4643.393534,5305.445256,6281.290855,6434.501797,6360.943444,6618.743050,7113.692252,6994.774861,8948.102923
75%,3939.978789,4756.525781,5180.755910,5788.093330,6809.406690,7674.929108,8997.897412,7807.095818,8137.004775,9767.297530,8797.640716,11977.574960
max,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090

#### What if we want to save these summary statistics to a new CSV file for ourselves?

In [17]:
stats = americas.describe()

In [19]:
help(stats.to_csv)

Help on method to_csv in module pandas.core.frame:

to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression=None, quoting=None, quotechar='"', line_terminator='\n', chunksize=None, tupleize_cols=False, date_format=None, doublequote=True, escapechar=None, decimal='.') method of pandas.core.frame.DataFrame instance
    Write DataFrame to a comma-separated values (csv) file

    Parameters
    ----------
    path_or_buf : string or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.
    sep : character, default ','
        Field delimiter for the output file.
    na_rep : string, default ''
        Missing data representation
    float_format : string, default None
        Format string for floating point numbers
    columns : sequence, optional
        Columns to write
    header : boolean or list of string, default True
        Write out column names. If a list of string is given it is assumed
        to be aliases for the column names
    index : boolean, default True
        Write row names (index)
    index_label : string or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the DataFrame uses MultiIndex.  If
        False do not print fields for index names. Use index_label=False
        for easier importing in R
    mode : str
        Python write mode, default 'w'
    encoding : string, optional
        A string representing the encoding to use in the output file,
        defaults to 'ascii' on Python 2 and 'utf-8' on Python 3.
    compression : string, optional
        a string representing the compression to use in the output file,
        allowed values are 'gzip', 'bz2', 'xz',
        only used when the first argument is a filename
    line_terminator : string, default ``'\n'``
        The newline character or character sequence to use in the output
        file
    quoting : optional constant from csv module
        defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric
    quotechar : string (length 1), default '\"'
        character used to quote fields
    doublequote : boolean, default True
        Control quoting of `quotechar` inside a field
    escapechar : string (length 1), default None
        character used to escape `sep` and `quotechar` when appropriate
    chunksize : int or None
        rows to write at a time
    tupleize_cols : boolean, default False
        write multi_index columns as a list of tuples (if True)
        or new (expanded format) if False)
    date_format : string, default None
        Format string for datetime objects
    decimal: string, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data

        .. versionadded:: 0.16.0

In [20]:
stats.to_csv('data/americas_summary_stats.csv')

#### What if we just want to see the first few rows of our Americas DataFrame?

In [22]:
help(americas.head)

Help on method head in module pandas.core.generic:

head(n=5) method of pandas.core.frame.DataFrame instance
    Returns first n rows

In [23]:
americas.head()

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850

In [24]:
help(americas.tail)

Help on method tail in module pandas.core.generic:

tail(n=5) method of pandas.core.frame.DataFrame instance
    Returns last n rows

In [25]:
americas.tail()

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Puerto Rico,Americas,3081.959785,3907.156189,5108.344630,6929.277714,9123.041742,9770.524921,10330.989150,12281.341910,14641.587110,16999.433300,18855.606180,19328.70901
Trinidad and Tobago,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,8792.573126,11460.600230,18008.50924
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.65309
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.46299
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.80569

#### What about if we want to see the first few columns?

In [29]:
americas_flipped = americas.T

In [32]:
americas_flipped

country,Argentina,Bolivia,Brazil,Canada,Chile,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,...,Mexico,Nicaragua,Panama,Paraguay,Peru,Puerto Rico,Trinidad and Tobago,United States,Uruguay,Venezuela
continent,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,...,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas
gdpPercap_1952,5911.32,2677.33,2108.94,11367.2,3939.98,2144.12,2627.01,5586.54,1397.72,3522.11,...,3478.13,3112.36,2480.38,1952.31,3758.52,3081.96,3023.27,13990.5,5716.77,7689.8
gdpPercap_1957,6856.86,2127.69,2487.37,12490,4315.62,2323.81,2990.01,6092.17,1544.4,3780.55,...,4131.55,3457.42,2961.8,2046.15,4245.26,3907.16,4100.39,14847.1,6150.77,9802.47
gdpPercap_1962,7133.17,2180.97,3336.59,13462.5,4519.09,2492.35,3460.94,5180.76,1662.14,4086.11,...,4581.61,3634.36,3536.54,2148.03,4957.04,5108.34,4997.52,16173.1,5603.36,8422.97
gdpPercap_1967,8052.95,2586.89,3429.86,16076.6,5106.65,2678.73,4161.73,5690.27,1653.72,4579.07,...,5754.73,4643.39,4421.01,2299.38,5788.09,6929.28,5621.37,19530.4,5444.62,9541.47
gdpPercap_1972,9443.04,2980.33,4985.71,18970.6,5494.02,3264.66,5118.15,5305.45,2189.87,5280.99,...,6809.41,4688.59,5364.25,2523.34,5937.83,9123.04,6619.55,21806,5703.41,10505.3
gdpPercap_1977,10079,3548.1,6660.12,22090.9,4756.76,3815.81,5926.88,6380.49,2681.99,6679.62,...,7674.93,5486.37,5351.91,3248.37,6281.29,9770.52,7899.55,24072.6,6504.34,13144
gdpPercap_1982,8997.9,3156.51,7030.84,22898.8,5095.67,4397.58,5262.73,7316.92,2861.09,7213.79,...,9611.15,3470.34,7009.6,4258.5,6434.5,10331,9119.53,25009.6,6920.22,11152.4
gdpPercap_1987,9139.67,2753.69,7807.1,26626.5,5547.06,4903.22,5629.92,7532.92,2899.84,6481.78,...,8688.16,2955.98,7034.78,3998.88,6360.94,12281.3,7388.6,29884.4,7452.4,9883.58
gdpPercap_1992,9308.42,2961.7,6950.28,26342.9,7596.13,5444.65,6160.42,5592.84,3044.21,7103.7,...,9472.38,2170.15,6618.74,4196.41,4446.38,14641.6,7370.99,32003.9,8137,10733.9
gdpPercap_1997,10967.3,3326.14,7957.98,28954.9,10118.1,6117.36,6677.05,5431.99,3614.1,7429.46,...,9767.3,2253.02,7113.69,4247.4,5838.35,16999.4,8792.57,35767.4,9230.24,10165.5
gdpPercap_2002,8797.64,3413.26,8131.21,33329,10778.8,5755.26,7723.45,6340.65,4563.81,5773.04,...,10742.4,2474.55,7356.03,3783.67,5909.02,18855.6,11460.6,39097.1,7727,8605.05
gdpPercap_2007,12779.4,3822.14,9065.8,36319.2,13171.6,7006.58,9645.06,8948.1,6025.37,6873.26,...,11977.6,2749.32,9809.19,4172.84,7408.91,19328.7,18008.5,42951.7,10611.5,11415.8

In [31]:
first_five = americas_flipped.head()

In [34]:
first_five

country,Argentina,Bolivia,Brazil,Canada,Chile,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,...,Mexico,Nicaragua,Panama,Paraguay,Peru,Puerto Rico,Trinidad and Tobago,United States,Uruguay,Venezuela
continent,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,...,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas,Americas
gdpPercap_1952,5911.32,2677.33,2108.94,11367.2,3939.98,2144.12,2627.01,5586.54,1397.72,3522.11,...,3478.13,3112.36,2480.38,1952.31,3758.52,3081.96,3023.27,13990.5,5716.77,7689.8
gdpPercap_1957,6856.86,2127.69,2487.37,12490,4315.62,2323.81,2990.01,6092.17,1544.4,3780.55,...,4131.55,3457.42,2961.8,2046.15,4245.26,3907.16,4100.39,14847.1,6150.77,9802.47
gdpPercap_1962,7133.17,2180.97,3336.59,13462.5,4519.09,2492.35,3460.94,5180.76,1662.14,4086.11,...,4581.61,3634.36,3536.54,2148.03,4957.04,5108.34,4997.52,16173.1,5603.36,8422.97
gdpPercap_1967,8052.95,2586.89,3429.86,16076.6,5106.65,2678.73,4161.73,5690.27,1653.72,4579.07,...,5754.73,4643.39,4421.01,2299.38,5788.09,6929.28,5621.37,19530.4,5444.62,9541.47

In [36]:
first_five.T

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967
country,,,,,
Argentina,Americas,5911.32,6856.86,7133.17,8052.95
Bolivia,Americas,2677.33,2127.69,2180.97,2586.89
Brazil,Americas,2108.94,2487.37,3336.59,3429.86
Canada,Americas,11367.2,12490,13462.5,16076.6
Chile,Americas,3939.98,4315.62,4519.09,5106.65
Colombia,Americas,2144.12,2323.81,2492.35,2678.73
Costa Rica,Americas,2627.01,2990.01,3460.94,4161.73
Cuba,Americas,5586.54,6092.17,5180.76,5690.27
Dominican Republic,Americas,1397.72,1544.4,1662.14,1653.72
Ecuador,Americas,3522.11,3780.55,4086.11,4579.07
El Salvador,Americas,3048.3,3421.52,3776.8,4358.6
Guatemala,Americas,2428.24,2617.16,2750.36,3242.53
Haiti,Americas,1840.37,1726.89,1796.59,1452.06
Honduras,Americas,2194.93,2220.49,2291.16,2538.27
Jamaica,Americas,2898.53,4756.53,5246.11,6124.7
Mexico,Americas,3478.13,4131.55,4581.61,5754.73
Nicaragua,Americas,3112.36,3457.42,3634.36,4643.39
Panama,Americas,2480.38,2961.8,3536.54,4421.01
Paraguay,Americas,1952.31,2046.15,2148.03,2299.38
Peru,Americas,3758.52,4245.26,4957.04,5788.09
Puerto Rico,Americas,3081.96,3907.16,5108.34,6929.28
Trinidad and Tobago,Americas,3023.27,4100.39,4997.52,5621.37
United States,Americas,13990.5,14847.1,16173.1,19530.4
Uruguay,Americas,5716.77,6150.77,5603.36,5444.62
Venezuela,Americas,7689.8,9802.47,8422.97,9541.47

#### What if we want to see the last few columns?

In [37]:
last_five = americas_flipped.tail()

In [38]:
last_five

country,Argentina,Bolivia,Brazil,Canada,Chile,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,...,Mexico,Nicaragua,Panama,Paraguay,Peru,Puerto Rico,Trinidad and Tobago,United States,Uruguay,Venezuela
gdpPercap_1987,9139.67,2753.69,7807.1,26626.5,5547.06,4903.22,5629.92,7532.92,2899.84,6481.78,...,8688.16,2955.98,7034.78,3998.88,6360.94,12281.3,7388.6,29884.4,7452.4,9883.58
gdpPercap_1992,9308.42,2961.7,6950.28,26342.9,7596.13,5444.65,6160.42,5592.84,3044.21,7103.7,...,9472.38,2170.15,6618.74,4196.41,4446.38,14641.6,7370.99,32003.9,8137,10733.9
gdpPercap_1997,10967.3,3326.14,7957.98,28954.9,10118.1,6117.36,6677.05,5431.99,3614.1,7429.46,...,9767.3,2253.02,7113.69,4247.4,5838.35,16999.4,8792.57,35767.4,9230.24,10165.5
gdpPercap_2002,8797.64,3413.26,8131.21,33329,10778.8,5755.26,7723.45,6340.65,4563.81,5773.04,...,10742.4,2474.55,7356.03,3783.67,5909.02,18855.6,11460.6,39097.1,7727,8605.05
gdpPercap_2007,12779.4,3822.14,9065.8,36319.2,13171.6,7006.58,9645.06,8948.1,6025.37,6873.26,...,11977.6,2749.32,9809.19,4172.84,7408.91,19328.7,18008.5,42951.7,10611.5,11415.8

In [39]:
last_five.T

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,
Argentina,9139.67,9308.42,10967.3,8797.64,12779.4
Bolivia,2753.69,2961.7,3326.14,3413.26,3822.14
Brazil,7807.1,6950.28,7957.98,8131.21,9065.8
Canada,26626.5,26342.9,28954.9,33329,36319.2
Chile,5547.06,7596.13,10118.1,10778.8,13171.6
Colombia,4903.22,5444.65,6117.36,5755.26,7006.58
Costa Rica,5629.92,6160.42,6677.05,7723.45,9645.06
Cuba,7532.92,5592.84,5431.99,6340.65,8948.1
Dominican Republic,2899.84,3044.21,3614.1,4563.81,6025.37
Ecuador,6481.78,7103.7,7429.46,5773.04,6873.26
El Salvador,4140.44,4444.23,5154.83,5351.57,5728.35
Guatemala,4246.49,4439.45,4684.31,4858.35,5186.05
Haiti,1823.02,1456.31,1341.73,1270.36,1201.64
Honduras,3023.1,3081.69,3160.45,3099.73,3548.33
Jamaica,6351.24,7404.92,7121.92,6994.77,7320.88
Mexico,8688.16,9472.38,9767.3,10742.4,11977.6
Nicaragua,2955.98,2170.15,2253.02,2474.55,2749.32
Panama,7034.78,6618.74,7113.69,7356.03,9809.19
Paraguay,3998.88,4196.41,4247.4,3783.67,4172.84
Peru,6360.94,4446.38,5838.35,5909.02,7408.91
Puerto Rico,12281.3,14641.6,16999.4,18855.6,19328.7
Trinidad and Tobago,7388.6,7370.99,8792.57,11460.6,18008.5
United States,29884.4,32003.9,35767.4,39097.1,42951.7
Uruguay,7452.4,8137,9230.24,7727,10611.5
Venezuela,9883.58,10733.9,10165.5,8605.05,11415.8

#### What if we want to get rid of the 'continent' column from the Americas table?

In [43]:
americas.head()

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850

In [41]:
help(americas.drop)

Help on method drop in module pandas.core.generic:

drop(labels, axis=0, level=None, inplace=False, errors='raise') method of pandas.core.frame.DataFrame instance
    Return new object with labels in requested axis removed.

    Parameters
    ----------
    labels : single label or list-like
    axis : int or axis name
    level : int or level name, default None
        For MultiIndex
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and existing labels are dropped.

        .. versionadded:: 0.16.1

    Returns
    -------
    dropped : type of caller

In [42]:
americas.drop('continent', axis=1)

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
Canada,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
Chile,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850
Colombia,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,6117.361746,5755.259962,7006.580419
Costa Rica,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,6677.045314,7723.447195,9645.061420
Cuba,5586.538780,6092.174359,5180.755910,5690.268015,5305.445256,6380.494966,7316.918107,7532.924763,5592.843963,5431.990415,6340.646683,8948.102923
Dominican Republic,1397.717137,1544.402995,1662.137359,1653.723003,2189.874499,2681.988900,2861.092386,2899.842175,3044.214214,3614.101285,4563.808154,6025.374752
Ecuador,3522.110717,3780.546651,4086.114078,4579.074215,5280.994710,6679.623260,7213.791267,6481.776993,7103.702595,7429.455877,5773.044512,6873.262326
El Salvador,3048.302900,3421.523218,3776.803627,4358.595393,4520.246008,5138.922374,4098.344175,4140.442097,4444.231700,5154.825496,5351.568666,5728.353514
Guatemala,2428.237769,2617.155967,2750.364446,3242.531147,4031.408271,4879.992748,4820.494790,4246.485974,4439.450840,4684.313807,4858.347495,5186.050003
Haiti,1840.366939,1726.887882,1796.589032,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
Honduras,2194.926204,2220.487682,2291.156835,2538.269358,2529.842345,3203.208066,3121.760794,3023.096699,3081.694603,3160.454906,3099.728660,3548.330846
Jamaica,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,7121.924704,6994.774861,7320.880262
Mexico,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530,11977.574960
Nicaragua,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,2253.023004,2474.548819,2749.320965
Panama,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,7113.692252,7356.031934,9809.185636
Paraguay,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,4247.400261,3783.674243,4172.838464
Peru,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,5838.347657,5909.020073,7408.905561
Puerto Rico,3081.959785,3907.156189,5108.344630,6929.277714,9123.041742,9770.524921,10330.989150,12281.341910,14641.587110,16999.433300,18855.606180,19328.709010
Trinidad and Tobago,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,8792.573126,11460.600230,18008.509240
United States,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090
Uruguay,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.462990
Venezuela,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.805690